apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: hello-batman-api
  description: Hello World example for batman
spec:
  type: rest
  lifecycle: int-pat-live
  owner: team-0
  definition: |
   var batman = "batman";
   
   Console.WriteLine("I'm " + batman);
